### ISSUE TITLE
Download datasets from tape

### ISSUE THREAD

**Issue by rupurt** [zowe/zowe-client-python-sdk#249]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

I would like to download datasets from tape via z/OSMF

**Describe your enhancement idea**

Provide an equivalent API to the z/OS FTP server which offers [AUTOTAPEMOUNT](https://www.ibm.com/docs/en/zos/2.4.0?topic=protocol-autotapemount-ftp-client-server-statement)

**Describe alternatives you've considered**

None

**Comment by zFernand0** [comment]
Hey @rupurt,
Thanks for submitting the issue.

I'm trying to look for some APIs provided by the z/OS Management Facility and I can't seem to find anything that interacts with tapes. The only kinds of operation that it supports is purely for retrieval of data classes, storage classes, and storage groups (and their definitions) ([_source_](https://www.ibm.com/docs/en/search/tape?scope=SSLTBW_3.1.0&tag=izua700)).

Since the [_AUTOTAPEMOUNT_](https://www.ibm.com/docs/en/zos/2.4.0?topic=protocol-autotapemount-ftp-client-server-statement) capabilities are only provided via the FTP protocol, we may need a bit more time to plan this enhancement. Ideally, we can provide support for a broader set of functionality that goes through the FTP protocol.

That said, I do like the enhancement, and who knows, someday we may provide a `zowe-ftp-for-zowe-sdk` package on PyPi 😋

**Comment by rupurt** [comment]
Haha, I couldn't find any either which is why I was hoping y'all might have some insights. I guess for now we'd have to have the admin configure our mounts if we want to use tape with z/OSMF.

For something like `zowe-ftp-for-zowe-sdk` I've been using a modified version of this pypi package https://pypi.org/project/zosftplib/. The repo doesn't exist anymore but you can get the source from pypi. It was missing a bunch of things provided in the NodeJS ftp library https://github.com/IBM/zos-node-accessor. So I've been porting those as I need them.

I will ask my company if we can work with the zowe project to open source them.
