### ISSUE TITLE
issue: Jobs.list_jobs() return value is not JSON

### ISSUE THREAD

**Issue by sosadchuk** [zowe/zowe-client-python-sdk#27]
Hi,

Checked Jobs.list_jobs() method, but I believe this issue spreading more than I will mention here.

list_jobs() dosctring states:
```
Returns
        -------
        json
            A JSON containing a list of jobs on JES queue based on the given parameters
```

But in fact the return value is a list, and processing it with json.loads() will lead to exception:
```
TypeError: the JSON object must be str, bytes or bytearray, not list
```

Either docstring change needed, or behavior change and encapsulation of response with something like:
```
return f'{{"response":{response_json}}}'
```

**Comment by Myrausman** [comment]
@zFernand0  should i  update changelog as well ?

**Comment by t1m0thyj** [comment]
> @t1m0thyj , I am interested in addressing this issue. Could you please assign it to me? Also, I'd like to confirm whether I should modify the docstring or the return type of the method.

@Myrausman Thanks for contributing and sorry for not replying sooner. I've looked into this and the method is returning a JSON object, so we shouldn't need to import the `json` package or change any code in the method. We just need to change the doc string to say that it returns a JSON object.

Could you please close https://github.com/zowe/zowe-client-python-sdk/pull/251 and open a new PR that updates the docstrings? For all the places in jobs.py that say `A JSON containing`, this is a typo and it should say `A JSON object containing` instead 🙂

> should i update changelog as well ?

If your PR only updates docstrings, then no changelog update is required since there are no user-facing changes.
