### ISSUE TITLE
Leverage zowe.config.json

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-client-python-sdk#29]
The Zowe CLI has introduced a [new way to more easily store and share configuration information](https://github.com/zowe/zowe-cli/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md). The benefits of this feature are:
  - As a CLI/SDK user, you can manage your connection details efficiently in one location.
  - As a team leader, you can share a configuration file with your team members so that they can easily access mainframe services. You can add the file directly to your project in an SCM.
  - As a new team member, you can onboard quickly by consuming your team's configuration file.
  
  More details on this enhancement are also available in this [blog](https://medium.com/zowe/zowe-cli-getting-started-made-easy-f53d769c678e)
  
  I would like to leverage this new config across all Zowe client tech including the Python SDK and for examples to be provided in the doc.

**Comment by MikeBauerCA** [comment]
Refinement Notes:
Reimplementation of config.ts in Python
Dual-pathing would not be required to support old config since Python SDK is not yet LTS
Just needs to support loading of config (not writing) for MVP - but should allow for writing creds (e.g. zowe config secure)
Keytar doesn't necessarily save items in a language-agnostic way

**Comment by shalearkane** [comment]
Can I work on this issue?

**Comment by t1m0thyj** [comment]
Created several issues with the `team-config` label to break down some of the tasks: https://github.com/zowe/zowe-client-python-sdk/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-config

The functionality described in the comment above should be covered by issues #68, #69. #70, #71, #72
The other issues #73 and #74 are stretch goals

The Config.ts file referenced above lives in the Imperative repo which implements team config support for the Node.js SDK: https://github.com/zowe/imperative/blob/master/packages/config/src/Config.ts

Since dual pathing (to support both v1 and v2 profiles with a single API) is unnecessary, we can probably keep and deprecate the existing ZoweProfile API for now to maintain backwards compatibility.

A quick summary of team config (aka as v2 profiles, which supersede Zowe v1 profiles) can be found here: https://medium.com/zowe/zowe-cli-getting-started-made-easy-f53d769c678e

@shalearkane We are looking for help to make these enhancements, you should have received an email 🙂
